### ISSUE TITLE
Support for PHP 8.0

### ISSUE THREAD

**Issue by fisruk** [meadsteve/MonoSnag#16]
Hi, do you plan to bring the current master to a new version? It would be great to have PHP8 support outside a development branch.

**Comment by meadsteve** [comment]
@fisruk I've not been actively working on this library so I hadn't planned it. However I'd happily merge/help out with a v8 PR.

Historically I've made the master branch support the latest version of php and release this as a new major version of the library. So I'd likely release this as a v5 which supports php 8

**Comment by meadsteve** [comment]
sorry I should also add. If it's easy to have v7 and v8 support I won't bump the major version of this library.

**Comment by meadsteve** [comment]
😆 I think I also ran out of travis credit so I'll need to migrate this project to github actions testing

**Comment by meadsteve** [comment]
@fisruk I had forgotten the main branch already supported php 8. Tagged and release as v4.1.0 👍
