### ISSUE TITLE
Please update to latest bugsnag

### ISSUE THREAD

**Issue by it-can** [meadsteve/MonoSnag#5]
please update https://github.com/bugsnag/bugsnag-php to latest version 2.6.0...

thanks

**Comment by meadsteve** [comment]
@it-can this should already work with bugsnag 2.6.0. What problems are you having?

**Comment by it-can** [comment]
Your package only installs 2.2.5 ?

**Comment by meadsteve** [comment]
@it-can that's the minimum the package is compatible with. You can specify whatever version of bugsnag you want (up to 3.0.0) in your composer.json.

**Comment by it-can** [comment]
Aaah ok didnt know that! Thanks
