### ISSUE TITLE
Bugsnag 3.0

### ISSUE THREAD

**Issue by limenet** [meadsteve/MonoSnag#8]
Are you planning on updating this Monolog plugin for use with the [`^3.0` versions of `bugsnag-php`](https://github.com/bugsnag/bugsnag-php/releases)?

**Comment by meadsteve** [comment]
@limenet I haven't been using this plugin or bugsnag for a while so I hadn't made any plans yet.
The changes don't look too big to make https://github.com/bugsnag/bugsnag-php/blob/master/UPGRADING.md#2x-to-3x.

I'd happily accept a PR :-) If not I'll try and find some time to look at this.

**Comment by meadsteve** [comment]
This has been fixed via #9 thanks to @pdbreen
